[custom]
;国内-国外分流

;规则集定义
ruleset=🟢 全球直连,https://raw.githubusercontent.com/HugoXu-hub/openclash-rules/main/rules/Direct_custom.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/HugoXu-hub/openclash-rules/main/rules/Proxy_custom.list
ruleset=YouTube,https://raw.githubusercontent.com/HugoXu-hub/openclash-rules/main/rules/YouTube.list
ruleset=AI,https://raw.githubusercontent.com/HugoXu-hub/openclash-rules/main/rules/AI.list
ruleset=Netflix,https://raw.githubusercontent.com/HugoXu-hub/openclash-rules/main/rules/Netflix.list
ruleset=🟢 全球直连,https://raw.githubusercontent.com/HugoXu-hub/openclash-rules/main/rules/Direct.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/HugoXu-hub/openclash-rules/main/rules/Proxy.list
ruleset=🟢 全球直连,[]GEOSITE,CN
ruleset=🟢 全球直连,[]GEOIP,CN,no-resolve
ruleset=🚀 节点选择,[]FINAL


;策略组定义
custom_proxy_group=YouTube`select`[]♻️ 自动选择`[]DIRECT`.*`https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/Large/YouTube.png
custom_proxy_group=AI`select`[]♻️ 自动选择`[]DIRECT`.*`https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/Large/AI.png
custom_proxy_group=Netflix`select`[]♻️ 自动选择`[]DIRECT`.*`https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/Large/Netflix.png
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=🟢 全球直连`select`[]DIRECT
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50

enable_rule_generator=true
overwrite_original_rules=true
